name: base
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  #- python=3.10
  - pip
  - Cython
  - psycopg2
  - aim
  - mlflow
  - jupyterlab
  - pytorch
  - torchvision
  - torchaudio
  - scikit-learn
  - matplotlib
  - seaborn
  - pandas
  - numpy
  - scipy
  - tqdm
  - ipywidgets
  - ipython
  - ipykernel
  - jupyterlab
  - pip:
    - aim-mlflow

